sudo: required
services:
  - docker

before_install:
  - docker build -t kristian/docker-react -f Dockerfile.dev . 

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker run -e CI=true kristian/docker-react npm run test -- --coverage
