sudo: required
services:
  - docker

before_install:
  - docker build -t kristian/docker-react -f Dockerfile.dev . 

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker run -e CI=true kristian/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-139029094532"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY